# Generated by Django 2.1.2 on 2018-10-31 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20181028_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='good',
        ),
    ]
