# Generated by Django 2.1.2 on 2018-10-31 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_remove_post_good'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
